# Config Yocto générée par yocto-tui
# Fichier : configs/config_yocto_default.ini

[general]
name = default
workdir = /home/clement/yocto-lab
poky_url = https://git.yoctoproject.org/poky
poky_branch = scarthgap
yocto_tag = 
machine = qemux86-64
threads = 8

[build]
build_dir = /home/clement/yocto-lab/builds/build-qemux86-64
dl_dir = /home/clement/yocto-lab/cache/downloads
sstate_dir = /home/clement/yocto-lab/cache/sstate-cache
image_recipe = core-image-minimal

[options]
install_packages = true
configure_locale = true
fix_apparmor = true
configure_git = true
first_build = false

[git]
user_name = unknown
user_email = unknown@example.com
